# Find any valid version of Qt (4 or 5)

find_package(Qt5Core QUIET)
if(Qt5Core_FOUND)
    cmake_minimum_required(VERSION 2.8.11 FATAL_ERROR)

    find_package(Qt5Gui REQUIRED)
    find_package(Qt5Widgets REQUIRED)
    find_package(Qt5Network REQUIRED)
    set(QT_FOUND_OK TRUE)
    set(QT5 TRUE)
    set(QT4 FALSE)
    set(QT_LIBS ${Qt5Widgets_LIBRARIES} ${Qt5Gui_LIBRARIES} ${Qt5Core_LIBRARIES} ${Qt5Network_LIBRARIES})
    set(QT_INCLUDE ${Qt5Core_INCLUDE_DIRS} ${Qt5Gui_INCLUDE_DIRS} ${Qt5Widgets_INCLUDE_DIRS} ${Qt5Network_INCLUDE_DIRS})
	message("Qt5 found, enabling Qt GUI.")

    macro(qt_res)
        qt5_add_resources(${ARGN})
    endmacro()

    macro(qt_moc)
        qt5_wrap_cpp(${ARGN})
    endmacro()

    macro(qt_ui)
        qt5_wrap_ui(${ARGN})
    endmacro()
else()
    find_package(Qt4 4.8.0 COMPONENTS QtCore QtGui REQUIRED)
    if(QT4_FOUND AND QT_QTCORE_FOUND AND QT_QTGUI_FOUND)
      set(QT_FOUND_OK TRUE)
      set(QT5 FALSE)
      set(QT4 TRUE)
      message("Qt4 found, enabling Qt GUI.")
    endif()
	include(${QT_USE_FILE})

	set(QT_LIBS ${QT_QTCORE_LIBRARY} ${QT_QTGUI_LIBRARIES} ${QT_QTNETWORK_LIBRARY})
	set(QT_INCLUDE ${QT_QTCORE_INCLUDE_DIR} ${QT_QTGUI_INCLUDE_DIR} ${QT_QTNETWORK_INCLUDE_DIR})

    macro(qt_res)
        qt4_add_resources(${ARGN})
    endmacro()

    macro(qt_moc)
        qt4_wrap_cpp(${ARGN})
    endmacro()

    macro(qt_ui)
        qt4_wrap_ui(${ARGN})
    endmacro()
endif()
